spring.application.name=demo
spring.main.web-application-type=none

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stocktraderdb}
spring.datasource.username=root
spring.datasource.password=joel#2006

spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
